### ISSUE TITLE
Provide response types

### ISSUE THREAD

**Issue by aurexav** [hack-ink/githuber#16]

**Comment by danielocfb** [comment]
I assume this issue tracks providing structured types for results reported by GitHub so that clients don't have to deal with `serde_json::Value`, is that correct? If so, this would indeed be very important, I'd argue.

**Comment by acgxv** [comment]
> I assume this issue tracks providing structured types for results reported by GitHub so that clients don't have to deal with `serde_json::Value`, is that correct? If so, this would indeed be very important, I'd argue.

Yes. But the GitHub API official docs didn't provide the response docs either. So, I'm not sure if I should treat them as JSON objects.

For example, this one https://docs.github.com/en/rest/commits/commits#compare-two-commits. They only gave a response example instead of docs (like the request parameters).

**Comment by acgxv** [comment]
I think it isn't a bad thing for downstream.

They can customize the response type. Remove the useless information themselves.

https://github.com/hack-ink/subalfred/blob/d1cdb3592f1def6e8756669c760568e21607800a/lib/core/src/github/mod.rs#L93-L119
